name: Playwright Tests
concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Playwright Setup Accounts
        run: yarn playwright test e2e/testSetupAccounts.spec.ts
      - name: Playwright Setup Cards
        run: yarn playwright test e2e/testSetupCards.spec.ts
      - name: debug-show-playwright-report-folder
        if: always()
        run: ls -lf playwright-report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v2
      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: playwright-report/
      #- name: Deploy to GitHub Pages
      #  if: always()
      #  id: deployment
      #  uses: actions/deploy-pages@v1
      - name: Stuff
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./playwright-report
           keep_files: false
           enable_jekyll: true
           user_name: 'github-actions[bot]'
           user_email: 'github-actions[bot]@users.noreply.github.com'
