name: Playwright Tests
concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Playwright Setup Accounts
        run: yarn playwright test e2e/testSetupAccounts.spec.ts
      - name: Playwright Setup Cards
        run: yarn playwright test e2e/testSetupCards.spec.ts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Check Folders
        if: always()
        run: ls -lf playwright-report/
      - name: Generate report directory name
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          CURRENT_DATE=$(date +"%H%M%d%m%Y")
          REPORT_DIRECTORY=playwright-report-$CURRENT_DATE-$COMMIT_ID
          mkdir $REPORT_DIRECTORY
      - name: Move report files to new directory
        run: |
          cp -r playwright-report/* $REPORT_DIRECTORY/
      - name: debug-show-playwright-report-folder
        if: always()
        run: ls -lf $REPORT_DIRECTORY/
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: $REPORT_DIRECTORY/
          retention-days: 30
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v2
      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: $REPORT_DIRECTORY/
      - name: Create Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.1
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: $REPORT_DIRECTORY
           keep_files: false
           enable_jekyll: true
           user_name: 'github-actions[bot]'
           user_email: 'github-actions[bot]@users.noreply.github.com'